/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package LiveLinkedData;

import fr.inria.acacia.corese.exceptions.EngineException;
import fr.inria.edelweiss.kgram.core.Mapping;
import fr.inria.edelweiss.kgram.core.Mappings;
import fr.inria.edelweiss.kgraph.core.Graph;
import fr.inria.edelweiss.kgtool.print.ResultFormat;
import fr.inria.edelweiss.kgtool.print.TripleFormat;
import java.io.IOException;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ibanez-l
 */
public class BroadcastStoreGUI extends javax.swing.JFrame {

  BroadcastStore graph;	
  
  /**
   * Creates new form StoreGUI
   */
  public BroadcastStoreGUI(String name, int port) {
	initComponents();
	try {
	  graph = new BroadcastStore(name,port);
	  InetAddress address = InetAddress.getLocalHost();
	  this.setTitle(name + "@" + address.getHostAddress()+":"+port);
	} catch (IOException ex) {
	  Logger.getLogger(BroadcastStoreGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    queryString = new javax.swing.JTextArea();
    jLabel1 = new javax.swing.JLabel();
    executeButton = new javax.swing.JButton();
    refreshButton = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    storeContent = new javax.swing.JTextPane();
    addFollowerButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    followList = new javax.swing.JTextPane();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    quadContent = new javax.swing.JTextPane();
    jLabel4 = new javax.swing.JLabel();
    followerAddr = new javax.swing.JTextField();
    jScrollPane5 = new javax.swing.JScrollPane();
    resultPane = new javax.swing.JTextPane();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    queryString.setColumns(20);
    queryString.setRows(5);
    jScrollPane1.setViewportView(queryString);

    jLabel1.setText("Query");

    executeButton.setText("Execute");
    executeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        executeButtonActionPerformed(evt);
      }
    });

    refreshButton.setText("Refresh");
    refreshButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        refreshButtonActionPerformed(evt);
      }
    });

    jScrollPane3.setViewportView(storeContent);

    addFollowerButton.setText("addFollower");
    addFollowerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addFollowerButtonActionPerformed(evt);
      }
    });

    jLabel2.setText("Followers");

    jScrollPane2.setViewportView(followList);

    jLabel3.setText("RDF Triples");

    jScrollPane4.setViewportView(quadContent);

    jLabel4.setText("SU-Set Quads");

    jScrollPane5.setViewportView(resultPane);

    jLabel5.setText("Result");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(121, 121, 121)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel4)
        .addGap(147, 147, 147))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                      .addGap(32, 32, 32)
                      .addComponent(addFollowerButton))
                    .addGroup(layout.createSequentialGroup()
                      .addGap(12, 12, 12)
                      .addComponent(followerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(31, 31, 31)
                  .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(executeButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addGap(125, 125, 125))))))
          .addGroup(layout.createSequentialGroup()
            .addGap(319, 319, 319)
            .addComponent(refreshButton)))
        .addContainerGap(31, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addComponent(executeButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(56, 56, 56)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGap(84, 84, 84)
            .addComponent(jLabel2))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(followerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(addFollowerButton))
          .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(refreshButton)
            .addGap(36, 36, 36)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
	try {
	  Mappings map = graph.query(queryString.getText());
	  //TripleFormat f1 = TripleFormat.create((Graph)map.getGraph());
	  ResultFormat rf = ResultFormat.create(map);
	  resultPane.setText(rf.toString());
			  

	  // Triples in the Store
	  TripleFormat f = TripleFormat.create(graph.getGraph());
	  storeContent.setText(f.toString());

	  // Quads in the Store
	  String res = "";
	  map = graph.query("SELECT * WHERE{tuple(?p ?s ?o ?id)}", true);
	  for(Mapping m : map){
	  	res += m.getValue("?s").toString() + " ";
	  	res += m.getValue("?p").toString() + " ";
	  	res += m.getValue("?o").toString() + " ";
	  	res += m.getValue("?id").toString() + "\n";
	  }
	  quadContent.setText(res);
	} catch (EngineException ex) {
	  Logger.getLogger(BroadcastStoreGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
  }//GEN-LAST:event_executeButtonActionPerformed

  private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
    // TODO add your handling code here:
	  TripleFormat f = TripleFormat.create(graph.getGraph());
	  storeContent.setText(f.toString());
	try {
	  String res = "";
	  Mappings map = graph.query("SELECT * WHERE{tuple(?p ?s ?o ?id)}", true);
	  for(Mapping m : map){
	  	res += m.getValue("?s").toString() + " ";
	  	res += m.getValue("?p").toString() + " ";
	  	res += m.getValue("?o").toString() + " ";
	  	res += m.getValue("?id").toString() + "\n";
	  }
	  quadContent.setText(res);
	} catch (EngineException ex) {
	  Logger.getLogger(BroadcastStoreGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
  }//GEN-LAST:event_refreshButtonActionPerformed

  private void addFollowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFollowerButtonActionPerformed
    // TODO add your handling code here:
	// Formatted values are a mess...
	String p = followerAddr.getText();
	graph.addFollower(p);
	String follow = "";
	for(String f : graph.getFollowers()){
		follow += f + " ; ";
	}
	followList.setText(follow);
  }//GEN-LAST:event_addFollowerButtonActionPerformed

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	/*
	try {
	  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		  javax.swing.UIManager.setLookAndFeel(info.getClassName());
		  break;
		}
	  }
	} catch (ClassNotFoundException ex) {
	  java.util.logging.Logger.getLogger(StoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	  java.util.logging.Logger.getLogger(StoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	  java.util.logging.Logger.getLogger(StoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	  java.util.logging.Logger.getLogger(StoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	/*
	java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
		new StoreGUI().setVisible(true);
  }
	});
  */
// }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addFollowerButton;
  private javax.swing.JButton executeButton;
  private javax.swing.JTextPane followList;
  private javax.swing.JTextField followerAddr;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextPane quadContent;
  private javax.swing.JTextArea queryString;
  private javax.swing.JButton refreshButton;
  private javax.swing.JTextPane resultPane;
  private javax.swing.JTextPane storeContent;
  // End of variables declaration//GEN-END:variables
}
